# supabase/config.toml
# This is the main configuration file for your Supabase project.

[functions.login-with-role]
  entrypoint = "./functions/login-with-role/index.js"
  verify_jwt = false

[functions.create-user]
  entrypoint = "./functions/create-user/index.js"
  # verify_jwt = false # Keep this commented out or set to false if you call it with user's JWT