
# supabase/config.toml
# This is the main configuration file for your Supabase project.

[functions.create-user]
entrypoint = "./functions/create-user/index.js"

[functions.sync-user-to-mongo]
entrypoint = "./functions/sync-user-to-mongo/index.js"